name: CI/CD Pipeline (EC2 only)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to EC2 and Build via SSH
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 400 key.pem
        scp -o StrictHostKeyChecking=no -i key.pem -r . $EC2_USER@$EC2_HOST:/home/$EC2_USER/ant-helper-backend/
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd /home/$EC2_USER/ant-helper-backend/backend
          ./gradlew clean build
          pkill -f 'java -jar build/libs/backend-0.0.1-SNAPSHOT.jar' || true
          nohup java -jar build/libs/backend-0.0.1-SNAPSHOT.jar > /home/$EC2_USER/nohup.out 2>&1 &
        EOF
        rm key.pem
